In [1]:
from sklearn.datasets import load_iris
import pandas as pd

In [6]:
iris = load_iris()

In [12]:
#print(iris) #will not be able to load it directly , need to make the dataframe
irisDf = pd.DataFrame(iris.data,columns = iris.feature_names)
irisDf.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [ ]:
irisDf['species_code'] = iris.target  #your own name -> species_code
irisDf.head()

   sepal length (cm)  sepal width (cm)  ...  petal width (cm)  species_code
0                5.1               3.5  ...               0.2             0
1                4.9               3.0  ...               0.2             0
2                4.7               3.2  ...               0.2             0
3                4.6               3.1  ...               0.2             0
4                5.0               3.6  ...               0.2             0

[5 rows x 5 columns]

In [15]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [16]:
irisDf.describe()

       sepal length (cm)  sepal width (cm)  ...  petal width (cm)  species_code
count         150.000000        150.000000  ...        150.000000    150.000000
mean            5.843333          3.057333  ...          1.199333      1.000000
std             0.828066          0.435866  ...          0.762238      0.819232
min             4.300000          2.000000  ...          0.100000      0.000000
25%             5.100000          2.800000  ...          0.300000      0.000000
50%             5.800000          3.000000  ...          1.300000      1.000000
75%             6.400000          3.300000  ...          1.800000      2.000000
max             7.900000          4.400000  ...          2.500000      2.000000

[8 rows x 5 columns]

In [18]:
irisDf.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   species_code       150 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 6.0 KB

In [17]:
irisDf.shape

(150, 5)

In [19]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [25]:
irisDf['species_name'] = irisDf['species_code'].map(dict(enumerate(iris.target_names)))
irisDf.tail()

     sepal length (cm)  sepal width (cm)  ...  species_code  species_name
145                6.7               3.0  ...             2     virginica
146                6.3               2.5  ...             2     virginica
147                6.5               3.0  ...             2     virginica
148                6.2               3.4  ...             2     virginica
149                5.9               3.0  ...             2     virginica

[5 rows x 6 columns]

In [26]:
irisDf[['petal length (cm)','petal length (cm)']]

     petal length (cm)  petal length (cm)
0                  1.4                1.4
1                  1.4                1.4
2                  1.3                1.3
3                  1.5                1.5
4                  1.4                1.4
..                 ...                ...
145                5.2                5.2
146                5.0                5.0
147                5.2                5.2
148                5.4                5.4
149                5.1                5.1

[150 rows x 2 columns]

In [27]:
irisDf.loc[0:5]

   sepal length (cm)  sepal width (cm)  ...  species_code  species_name
0                5.1               3.5  ...             0        setosa
1                4.9               3.0  ...             0        setosa
2                4.7               3.2  ...             0        setosa
3                4.6               3.1  ...             0        setosa
4                5.0               3.6  ...             0        setosa
5                5.4               3.9  ...             0        setosa

[6 rows x 6 columns]

In [ ]:
irisDf[irisDf['species_name'] == 'setosa']

     sepal length (cm)  sepal width (cm)  ...  species_code  species_name
0                  5.1               3.5  ...             0        setosa
1                  4.9               3.0  ...             0        setosa
2                  4.7               3.2  ...             0        setosa
3                  4.6               3.1  ...             0        setosa
4                  5.0               3.6  ...             0        setosa
..                 ...               ...  ...           ...           ...
145                6.7               3.0  ...             2        setosa
146                6.3               2.5  ...             2        setosa
147                6.5               3.0  ...             2        setosa
148                6.2               3.4  ...             2        setosa
149                5.9               3.0  ...             2        setosa

[150 rows x 6 columns]

In [ ]:
irisDf[irisDf['species_name'] == 'virginica'].count()

sepal length (cm)    150
sepal width (cm)     150
petal length (cm)    150
petal width (cm)     150
species_code         150
species_name         150
dtype: int64