In [ ]:
import pandas as pd 
import numpy as np

Notes : 
sctural data , like csv , table etc 
Python data type -> list , tuple , num , dictionary
Pandas - series , dataframe [contant data and header]
How to create the Dataframe - Create the dict

In [13]:
print("normal dict")
myDataFrame = {
    "Name" : ["Saurav","Sanjay","Anu","Dh"],
    "NLUMarks" : ["97","10","35","36"],
    "AIMarks" : ["97","10","35","36"]
}

print(type(myDataFrame))
myDataFrame

print("pandas dataframe")
myPDDataFrame = pd.DataFrame({
    "Name" : ["Saurav","Sanjay","Anu","Dh"],
    "NLUMarks" : ["97","10","35","36"],
    "AIMarks" : ["97","10","35","36"]
})

print(type(myPDDataFrame))
myPDDataFrame

normal dict
<class 'dict'>
pandas dataframe
<class 'pandas.DataFrame'>

     Name NLUMarks AIMarks
0  Saurav       97      97
1  Sanjay       10      10
2     Anu       35      35
3      Dh       36      36

In [14]:
myPDDataFrame.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      4 non-null      str
 1   NLUMarks  4 non-null      str
 2   AIMarks   4 non-null      str
dtypes: str(3)
memory usage: 228.0 bytes

In [ ]:
myPDDataFrame.head() # first 5 rows

     Name NLUMarks AIMarks
0  Saurav       97      97
1  Sanjay       10      10
2     Anu       35      35
3      Dh       36      36

In [ ]:
#loading the data from CSV
data = pd.read_csv("data.csv")
data.head()

,address,year,day,length,weight,count,looped,neighbors,income,label
0,111K8kZAEnJg245r2cM6y9zgJGHZtJPy6,2017,11,18,0.008333,1,0,2,100050000.0,black
1,1123pJv8jzeFQaCV4w644pzQJzVWay2zcA,2016,132,44,0.000244,1,0,1,100000000.0,black
2,112536im7hy6wtKbpH1qYDWtTyMRAcA2p7,2016,246,0,1.000000,1,0,2,200000000.0,black
3,1126eDRw2wqSkWosjTCre8cjjQW8sSeWH7,2016,322,72,0.003906,1,0,2,71200000.0,black
4,1129TSjKtx65E35GiUo4AYVeyo48twbrGX,2016,238,144,0.072848,456,0,1,200000000.0,black

In [18]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1041413 entries, 0 to 1041412
Data columns (total 10 columns):
 #   Column     Non-Null Count    Dtype
---  ------     --------------    -----
 0   address    1041413 non-null  str
 1   year       1041413 non-null  int64
 2   day        1041413 non-null  int64
 3   length     1041413 non-null  int64
 4   weight     1041413 non-null  float64
 5   count      1041413 non-null  int64
 6   looped     1041413 non-null  int64
 7   neighbors  1041413 non-null  int64
 8   income     1041413 non-null  float64
 9   label      1041413 non-null  str
dtypes: float64(2), int64(6), str(2)
memory usage: 79.5 MB

In [22]:
data.head(10)

,address,year,day,length,weight,count,looped,neighbors,income,label
0,111K8kZAEnJg245r2cM6y9zgJGHZtJPy6,2017,11,18,8.333333e-03,1,0,2,100050000.0,black
1,1123pJv8jzeFQaCV4w644pzQJzVWay2zcA,2016,132,44,2.441406e-04,1,0,1,100000000.0,black
2,112536im7hy6wtKbpH1qYDWtTyMRAcA2p7,2016,246,0,1.000000e+00,1,0,2,200000000.0,black
3,1126eDRw2wqSkWosjTCre8cjjQW8sSeWH7,2016,322,72,3.906250e-03,1,0,2,71200000.0,black
4,1129TSjKtx65E35GiUo4AYVeyo48twbrGX,2016,238,144,7.284841e-02,456,0,1,200000000.0,black
5,112AmFATxzhuSpvtz1hfpa3Zrw3BG276pc,2016,96,144,8.461400e-02,2821,0,1,50000000.0,black
6,112E91jxS2qrQY1z78LPWUWrLVFGqbYPQ1,2016,225,142,2.088519e-03,881,0,2,100000000.0,black
7,112eFykaD53KEkKeYW9KW8eWebZYSbt2f5,2016,324,78,3.906250e-03,1,0,2,100990000.0,black
8,112FTiRdJjMrNgEtd4fvdoq3TC33Ah5Dep,2016,298,144,2.302828e+00,4220,0,2,80000000.0,black
9,112GocBgFSnaote6krx828qaockFraD8mp,2016,62,112,3.725290e-09,1,0,1,50000000.0,black

In [26]:
#i want to find how many labels are white and how many are black

data["label"].unique()

<StringArray>
['black', 'white']
Length: 2, dtype: str

In [27]:
#how many label black how many white 
data["label"].value_counts()

label
white    1000000
black      41413
Name: count, dtype: int64

In [29]:
data["year"].head()

0    2017
1    2016
2    2016
3    2016
4    2016
Name: year, dtype: int64

In [ ]:
# does the numerical analysis of the data , will be only on the numerical type 
data.describe()

,year,day,length,weight,count,looped,neighbors,income
count,1.041413e+06,1.041413e+06,1.041413e+06,1.041413e+06,1.041413e+06,1.041413e+06,1.041413e+06,1.041413e+06
mean,2.014486e+03,1.813671e+02,4.493744e+01,5.451550e-01,7.193436e+02,2.351892e+02,2.188310e+00,4.470532e+09
std,2.239959e+00,1.037746e+02,5.897810e+01,3.067416e+00,1.686160e+03,9.628849e+02,1.361079e+01,1.742991e+11
min,2.011000e+03,1.000000e+00,0.000000e+00,8.973914e-88,1.000000e+00,0.000000e+00,1.000000e+00,3.000000e+07
25%,2.013000e+03,9.200000e+01,2.000000e+00,2.217425e-02,1.000000e+00,0.000000e+00,1.000000e+00,7.472574e+07
50%,2.014000e+03,1.810000e+02,8.000000e+00,2.500000e-01,1.000000e+00,0.000000e+00,2.000000e+00,1.996400e+08
75%,2.016000e+03,2.710000e+02,1.080000e+02,9.045818e-01,5.600000e+01,0.000000e+00,2.000000e+00,9.701200e+08
max,2.018000e+03,3.650000e+02,1.440000e+02,1.019849e+03,1.449600e+04,1.449600e+04,3.575000e+03,4.996440e+13

In [ ]:
#change the datatype of the year column
data['year'] = data['year'].astype('category')

data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1041413 entries, 0 to 1041412
Data columns (total 10 columns):
 #   Column     Non-Null Count    Dtype
---  ------     --------------    -----
 0   address    1041413 non-null  str
 1   year       1041413 non-null  category
 2   day        1041413 non-null  int64
 3   length     1041413 non-null  int64
 4   weight     1041413 non-null  float64
 5   count      1041413 non-null  int64
 6   looped     1041413 non-null  int64
 7   neighbors  1041413 non-null  int64
 8   income     1041413 non-null  float64
 9   label      1041413 non-null  str
dtypes: category(1), float64(2), int64(5), str(2)
memory usage: 72.5 MB

In [35]:
data['day'].unique()
data['day'] = data['day'].astype('category')
data['label'] = data['label'].astype('category')

data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1041413 entries, 0 to 1041412
Data columns (total 10 columns):
 #   Column     Non-Null Count    Dtype
---  ------     --------------    -----
 0   address    1041413 non-null  str
 1   year       1041413 non-null  category
 2   day        1041413 non-null  category
 3   length     1041413 non-null  int64
 4   weight     1041413 non-null  float64
 5   count      1041413 non-null  int64
 6   looped     1041413 non-null  int64
 7   neighbors  1041413 non-null  int64
 8   income     1041413 non-null  float64
 9   label      1041413 non-null  category
dtypes: category(3), float64(2), int64(4), str(1)
memory usage: 59.6 MB

In [ ]:
#duplicate date 
data.duplicated() #false means not duplicate

dup = data.duplicated() # will show the duplicate data
data[dup]

Empty DataFrame
Columns: [address, year, day, length, weight, count, looped, neighbors, income, label]
Index: []